// <auto-generated />
using System;
using DateSwipe.Server.Data.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DateSwipe.Server.Migrations
{
    [DbContext(typeof(DatingDbContext))]
    [Migration("20240802051723_ChatMessageRework")]
    partial class ChatMessageRework
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DateSwipe.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Outdoor"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Indoor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Romantic"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Adventurous"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Relaxing"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cultural"
                        });
                });

            modelBuilder.Entity("DateSwipe.Shared.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoupleId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("DateSwipe.Shared.DateIdea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DateIdeas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Enjoy a fine dining experience.",
                            ImageUrl = "https://images.unsplash.com/photo-1614387726083-c445e799102b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTQ3fHxDb3VwbGUlMjBEaW5uZXJ8ZW58MHx8MHx8fDA%3D",
                            Title = "Dinner at a fancy restaurant"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Explore nature on a hiking trail.",
                            ImageUrl = "https://images.unsplash.com/photo-1447302325121-30ef3bab8b65?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fEhpa2luZyUyMENvdXBsZXxlbnwwfHwwfHx8MA%3D%3D",
                            Title = "Hiking trip"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Watch the latest blockbuster.",
                            ImageUrl = "https://images.unsplash.com/photo-1689841497791-7aa38bfa4317?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Q2luZW1hJTIwQ291cGxlfGVufDB8fDB8fHwy",
                            Title = "Movie night"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Relax with a picnic in the park.",
                            ImageUrl = "https://images.unsplash.com/photo-1527574311754-da5f33012338?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fENvdXBsZSUyMFBpY05pY3xlbnwwfHwwfHx8MA%3D%3D&",
                            Title = "Picnic in the park"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Spend a day at the beach.",
                            ImageUrl = "https://images.unsplash.com/photo-1488116593952-937c38246bbe?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Q29va2luZyUyMGNvdXBsZXxlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Beach day"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Learn to cook a new dish together.",
                            ImageUrl = "https://images.unsplash.com/photo-1504753793650-d4f2d1d0b13d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y29va2luZyUyMGNsYXNzJTIwY291cGxlfGVufDB8fDB8fHww&",
                            Title = "Cooking class"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Sample different wines at a vineyard.",
                            ImageUrl = "https://images.unsplash.com/photo-1556710808-a2bc27a448f2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8d2luZSUyMHRhc3RpbmclMjBtYW4lMjB3b21hbnxlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Wine tasting"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Explore art and history at a museum.",
                            ImageUrl = "https://images.unsplash.com/photo-1706320291927-ea5b107db646?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTAyfHxtdXN1ZW18ZW58MHx8MHx8fDI%3D",
                            Title = "Museum visit"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Enjoy a fun night of bowling.",
                            ImageUrl = "https://images.unsplash.com/photo-1570472456794-8578e4bf1fab?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjE4fHxib3dsaW5nfGVufDB8fDB8fHwy",
                            Title = "Bowling night"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Watch the stars together in a quiet spot.",
                            ImageUrl = "https://images.unsplash.com/photo-1691518039261-350bd2190174?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8ODl8fHN0YXJnYXppbmd8ZW58MHx8MHx8fDI%3D",
                            Title = "Stargazing"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Have fun at an amusement park.",
                            ImageUrl = "https://images.unsplash.com/photo-1658134636987-a3f9aa63c9af?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjd8fGFtdXNtZW50JTIwcGFya3xlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Amusement park"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Attend a live music concert.",
                            ImageUrl = "https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGNvbmNlcnR8ZW58MHx8MHx8fDI%3D",
                            Title = "Concert"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Spend a night under the stars camping.",
                            ImageUrl = "https://images.unsplash.com/photo-1539183204366-63a0589187ab?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGNhbXBpbmd8ZW58MHx8MHx8fDI%3D",
                            Title = "Camping"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Enjoy ice skating together.",
                            ImageUrl = "https://images.unsplash.com/photo-1609987051964-7bc15e54e9bc?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8SWNlJTIwU2thdGluZyUyMGNvdXBsZXxlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Ice skating"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Sing your heart out at a karaoke bar.",
                            ImageUrl = "https://images.unsplash.com/photo-1516108759901-daf1a20f9281?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8c2luZ2luZyUyMGNvdXBsZXxlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Karaoke night"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Take a spontaneous road trip.",
                            ImageUrl = "https://images.unsplash.com/photo-1495610379499-a1f03b4732a7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fHJvYWR0cmlwfGVufDB8fDB8fHwy",
                            Title = "Road trip"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Experience a hot air balloon ride.",
                            ImageUrl = "https://images.unsplash.com/photo-1502119095323-253837f293f9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGhvdCUyMGFpciUyMGJhbGxvb258ZW58MHx8MHx8fDI%3D",
                            Title = "Hot air balloon ride"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Solve puzzles in an escape room.",
                            ImageUrl = "https://images.unsplash.com/photo-1580256079206-46a04a632758?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzV8fGVzY2FwZXJvb218ZW58MHx8MHx8fDI%3D",
                            Title = "Escape room"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Have fun playing mini golf.",
                            ImageUrl = "https://images.unsplash.com/photo-1647884756876-9b230e2f75a9?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bWluaWF0dXJlJTIwZ29sZnxlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Mini golf"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Make pottery together in a class.",
                            ImageUrl = "https://images.unsplash.com/photo-1635304438525-106382337f9b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8cG90dGVyeXxlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Pottery class"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Watch a live theater play.",
                            ImageUrl = "https://images.unsplash.com/photo-1503095396549-807759245b35?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dGhlYXRlcnxlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Theater play"
                        },
                        new
                        {
                            Id = 22,
                            Description = "See animals at the zoo.",
                            ImageUrl = "https://images.unsplash.com/photo-1503918756811-975bd3397178?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8em9vfGVufDB8fDB8fHwy",
                            Title = "Zoo visit"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Go for a bike ride together.",
                            ImageUrl = "https://images.unsplash.com/photo-1476345692822-c597e09a0331?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGJpa2luZ3xlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Biking"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Explore a local farmers market.",
                            ImageUrl = "https://images.unsplash.com/photo-1514583079045-e928a4732ade?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGZhcm1lcnMlMjBtYXJrZXR8ZW58MHx8MHx8fDI%3D",
                            Title = "Farmers market"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Go horseback riding.",
                            ImageUrl = "https://images.unsplash.com/photo-1633767979501-6225d151ba70?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aG9yc2ViYWNrJTIwcmlkaW5nfGVufDB8fDB8fHwy",
                            Title = "Horseback riding"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Cook a meal together at home.",
                            ImageUrl = "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGNvb2tpbmd8ZW58MHx8MHx8fDI%3D",
                            Title = "Cooking at home"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Play board games.",
                            ImageUrl = "https://images.unsplash.com/photo-1708863827400-00a5c21c10f7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGJvYXJkZ2FtZXN8ZW58MHx8MHx8fDI%3D",
                            Title = "Board games"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Volunteer at a local charity.",
                            ImageUrl = "https://images.unsplash.com/photo-1618477460930-d8bffff64172?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHZvbHVudGVlcmluZ3xlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Volunteer together"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Go fishing together.",
                            ImageUrl = "https://images.unsplash.com/photo-1657982469733-fbf83ebdab8f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZmlzaGluZ3xlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Fishing"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Take a dance class.",
                            ImageUrl = "https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGRhbmNlJTIwY2xhc3N8ZW58MHx8MHx8fDI%3D",
                            Title = "Dance class"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Take photos together.",
                            ImageUrl = "https://images.unsplash.com/photo-1719937206498-b31844530a96?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDF8MHxzZWFyY2h8MXx8cGhvdG9ncmFwaHl8ZW58MHx8MHx8fDI%3D",
                            Title = "Photography day"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Relax with a spa day.",
                            ImageUrl = "https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fHNwYXxlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Spa day"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Have a cooking competition.",
                            ImageUrl = "https://images.unsplash.com/photo-1576097449798-7c7f90e1248a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjR8fGNvb2tpbmclMjBjb21wZXRpdGlvbnxlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Cooking competition"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Enjoy a trivia night.",
                            ImageUrl = "https://images.unsplash.com/photo-1570937943292-a574bd5bc722?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dHJpdmlhfGVufDB8fDB8fHwy",
                            Title = "Trivia night"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Plant a garden together.",
                            ImageUrl = "https://images.unsplash.com/photo-1597868165956-03a6827955b1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Z2FyZGVuJTIwd29ya3xlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Plant a garden"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Visit an art gallery.",
                            ImageUrl = "https://images.unsplash.com/photo-1637680298164-74342b63a61a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YXJ0JTIwZ2FsbGVyeXxlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Art gallery"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Browse books at a bookstore.",
                            ImageUrl = "https://images.unsplash.com/photo-1671202867630-c897313a0a22?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Ym9va3N0b3JlfGVufDB8fDB8fHwy",
                            Title = "Bookstore date"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Go surfing together.",
                            ImageUrl = "https://images.unsplash.com/photo-1502933691298-84fc14542831?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHN1cmZpbmd8ZW58MHx8MHx8fDI%3D",
                            Title = "Surfing"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Experience jet skiing.",
                            ImageUrl = "https://images.unsplash.com/photo-1650939489556-a6fc47e28372?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8amV0JTIwc2tpaW5nfGVufDB8fDB8fHwy",
                            Title = "Jet skiing"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Go rock climbing.",
                            ImageUrl = "https://images.unsplash.com/photo-1522362485439-83fcff4673f0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cm9jayUyMGNsaW1iaW5nfGVufDB8fDB8fHwy",
                            Title = "Rock climbing"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Attend a yoga class together.",
                            ImageUrl = "https://images.unsplash.com/photo-1517363898874-737b62a7db91?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHlvZ2F8ZW58MHx8MHx8fDI%3D",
                            Title = "Yoga class"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Visit a dog park with your pets.",
                            ImageUrl = "https://images.unsplash.com/photo-1667230228326-c881966e2a29?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8ZG9ncGFya3xlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Dog park"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Explore an aquarium.",
                            ImageUrl = "https://images.unsplash.com/photo-1459207982041-089ff95be891?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YXF1YXJpdW18ZW58MHx8MHx8fDI%3D",
                            Title = "Aquarium visit"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Have fun at a trampoline park.",
                            ImageUrl = "https://images.unsplash.com/photo-1626817654900-c07008365317?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHRyYW1wb2xpbmV8ZW58MHx8MHx8fDI%3D",
                            Title = "Trampoline park"
                        },
                        new
                        {
                            Id = 46,
                            Description = "Play laser tag.",
                            ImageUrl = "https://images.unsplash.com/photo-1542810205-0a5b379f9c52?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGxhc2VyJTIwdGFnfGVufDB8fDB8fHwy",
                            Title = "Laser tag"
                        },
                        new
                        {
                            Id = 47,
                            Description = "Race go-karts together.",
                            ImageUrl = "https://images.unsplash.com/photo-1505570554449-69ce7d4fa36b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGdvJTIwa2FydHxlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Go-kart racing"
                        },
                        new
                        {
                            Id = 48,
                            Description = "Take a painting class.",
                            ImageUrl = "https://images.unsplash.com/photo-1476055090065-a605fefd840e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGFpbnRpbmclMjBhY3Rpdml0eXxlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Painting class"
                        },
                        new
                        {
                            Id = 50,
                            Description = "Go skiing together.",
                            ImageUrl = "https://images.unsplash.com/photo-1498576260462-eefc9d0ce9f7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8c2tpaW5nfGVufDB8fDB8fHwy",
                            Title = "Skiing"
                        });
                });

            modelBuilder.Entity("DateSwipe.Shared.DateIdeaCategory", b =>
                {
                    b.Property<int>("DateIdeaId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("DateIdeaId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("DateIdeaCategories");

                    b.HasData(
                        new
                        {
                            DateIdeaId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            DateIdeaId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            DateIdeaId = 3,
                            CategoryId = 2
                        },
                        new
                        {
                            DateIdeaId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            DateIdeaId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            DateIdeaId = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            DateIdeaId = 7,
                            CategoryId = 2
                        },
                        new
                        {
                            DateIdeaId = 8,
                            CategoryId = 6
                        },
                        new
                        {
                            DateIdeaId = 9,
                            CategoryId = 2
                        },
                        new
                        {
                            DateIdeaId = 10,
                            CategoryId = 1
                        },
                        new
                        {
                            DateIdeaId = 11,
                            CategoryId = 4
                        },
                        new
                        {
                            DateIdeaId = 12,
                            CategoryId = 6
                        },
                        new
                        {
                            DateIdeaId = 13,
                            CategoryId = 4
                        },
                        new
                        {
                            DateIdeaId = 14,
                            CategoryId = 6
                        },
                        new
                        {
                            DateIdeaId = 15,
                            CategoryId = 6
                        },
                        new
                        {
                            DateIdeaId = 16,
                            CategoryId = 4
                        },
                        new
                        {
                            DateIdeaId = 17,
                            CategoryId = 2
                        },
                        new
                        {
                            DateIdeaId = 18,
                            CategoryId = 4
                        },
                        new
                        {
                            DateIdeaId = 19,
                            CategoryId = 4
                        },
                        new
                        {
                            DateIdeaId = 20,
                            CategoryId = 4
                        });
                });

            modelBuilder.Entity("DateSwipe.Shared.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("DateSwipe.Shared.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P256DH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("DateSwipe.Shared.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoupleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSubscribed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DateSwipe.Shared.UserCategoryPreference", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("Liked")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("UserCategoryPreferences");
                });

            modelBuilder.Entity("DateSwipe.Shared.UserSwipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoupleId")
                        .HasColumnType("int");

                    b.Property<int>("DateIdeaId")
                        .HasColumnType("int");

                    b.Property<bool>("Liked")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSwipes");
                });

            modelBuilder.Entity("DateSwipe.Shared.DateIdeaCategory", b =>
                {
                    b.HasOne("DateSwipe.Shared.Category", "Category")
                        .WithMany("DateIdeaCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DateSwipe.Shared.DateIdea", "DateIdea")
                        .WithMany("DateIdeaCategories")
                        .HasForeignKey("DateIdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("DateIdea");
                });

            modelBuilder.Entity("DateSwipe.Shared.PushSubscription", b =>
                {
                    b.HasOne("DateSwipe.Shared.User", "User")
                        .WithMany("PushSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DateSwipe.Shared.UserCategoryPreference", b =>
                {
                    b.HasOne("DateSwipe.Shared.Category", "Category")
                        .WithMany("UserPreferences")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DateSwipe.Shared.User", "User")
                        .WithMany("CategoryPreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DateSwipe.Shared.UserSwipe", b =>
                {
                    b.HasOne("DateSwipe.Shared.User", "User")
                        .WithMany("UserSwipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DateSwipe.Shared.Category", b =>
                {
                    b.Navigation("DateIdeaCategories");

                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("DateSwipe.Shared.DateIdea", b =>
                {
                    b.Navigation("DateIdeaCategories");
                });

            modelBuilder.Entity("DateSwipe.Shared.User", b =>
                {
                    b.Navigation("CategoryPreferences");

                    b.Navigation("PushSubscriptions");

                    b.Navigation("UserSwipes");
                });
#pragma warning restore 612, 618
        }
    }
}
