// <auto-generated />
using System;
using DateSwipe.Server.Data.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DateSwipe.Server.Migrations
{
    [DbContext(typeof(DatingDbContext))]
    [Migration("20240725174811_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DateSwipe.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Outdoor"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Indoor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Romantic"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Adventurous"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Relaxing"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cultural"
                        });
                });

            modelBuilder.Entity("DateSwipe.Shared.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoupleId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("DateSwipe.Shared.DateIdea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DateIdeas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Enjoy a fine dining experience.",
                            ImageUrl = "https://images.unsplash.com/photo-1614387726083-c445e799102b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTQ3fHxDb3VwbGUlMjBEaW5uZXJ8ZW58MHx8MHx8fDA%3D",
                            Title = "Dinner at a fancy restaurant"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Explore nature on a hiking trail.",
                            ImageUrl = "https://images.unsplash.com/photo-1447302325121-30ef3bab8b65?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fEhpa2luZyUyMENvdXBsZXxlbnwwfHwwfHx8MA%3D%3D",
                            Title = "Hiking trip"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Watch the latest blockbuster.",
                            ImageUrl = "https://images.unsplash.com/photo-1689841497791-7aa38bfa4317?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Q2luZW1hJTIwQ291cGxlfGVufDB8fDB8fHwy",
                            Title = "Movie night"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Relax with a picnic in the park.",
                            ImageUrl = "https://images.unsplash.com/photo-1527574311754-da5f33012338?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fENvdXBsZSUyMFBpY05pY3xlbnwwfHwwfHx8MA%3D%3D&",
                            Title = "Picnic in the park"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Spend a day at the beach.",
                            ImageUrl = "https://images.unsplash.com/photo-1488116593952-937c38246bbe?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Q29va2luZyUyMGNvdXBsZXxlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Beach day"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Learn to cook a new dish together.",
                            ImageUrl = "https://images.unsplash.com/photo-1504753793650-d4f2d1d0b13d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y29va2luZyUyMGNsYXNzJTIwY291cGxlfGVufDB8fDB8fHww&",
                            Title = "Cooking class"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Sample different wines at a vineyard.",
                            ImageUrl = "https://images.unsplash.com/photo-1556710808-a2bc27a448f2?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8d2luZSUyMHRhc3RpbmclMjBtYW4lMjB3b21hbnxlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Wine tasting"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Explore art and history at a museum.",
                            ImageUrl = "https://images.unsplash.com/photo-1706320291927-ea5b107db646?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTAyfHxtdXN1ZW18ZW58MHx8MHx8fDI%3D",
                            Title = "Museum visit"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Enjoy a fun night of bowling.",
                            ImageUrl = "https://images.unsplash.com/photo-1570472456794-8578e4bf1fab?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjE4fHxib3dsaW5nfGVufDB8fDB8fHwy",
                            Title = "Bowling night"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Watch the stars together in a quiet spot.",
                            ImageUrl = "https://images.unsplash.com/photo-1691518039261-350bd2190174?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8ODl8fHN0YXJnYXppbmd8ZW58MHx8MHx8fDI%3D",
                            Title = "Stargazing"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Have fun at an amusement park.",
                            ImageUrl = "https://images.unsplash.com/photo-1658134636987-a3f9aa63c9af?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjd8fGFtdXNtZW50JTIwcGFya3xlbnwwfHwwfHx8MA%3D%3D",
                            Title = "Amusement park"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Watch a play or musical together.",
                            ImageUrl = "https://images.unsplash.com/photo-1625843706570-10ff8fd9b796?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTE2fHx0aGVhdGVyfGVufDB8fDB8fHwy",
                            Title = "Theater show"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Spend a night under the stars camping.",
                            ImageUrl = "https://images.unsplash.com/photo-1552176802-54b65e0f2024?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Njd8fGNhbXBpbmd8ZW58MHx8MHx8fDI%3D",
                            Title = "Camping trip"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Take an art class together.",
                            ImageUrl = "https://images.unsplash.com/photo-1504252060328-1455a645f4e3?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzl8fGFydCUyMGNvbXBsZXRpb258ZW58MHx8MHx8fDI%3D",
                            Title = "Art class"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Visit a zoo and see exotic animals.",
                            ImageUrl = "https://images.unsplash.com/photo-1570197786657-f0b067e3f2dc?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTN8fHpvb3xlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Zoo visit"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Go ice skating at a local rink.",
                            ImageUrl = "https://images.unsplash.com/photo-1600721651867-7ab4c12a67f1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGljZSUyMHNrYXRpbmd8ZW58MHx8MHx8fDI%3D",
                            Title = "Ice skating"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Sing your favorite songs at a karaoke bar.",
                            ImageUrl = "https://images.unsplash.com/photo-1563357999-7c1893e1b6ca?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OTB8fGthcmFva2V8ZW58MHx8MHx8fDI%3D",
                            Title = "Karaoke night"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Go for a bike ride together.",
                            ImageUrl = "https://images.unsplash.com/photo-1562059390-a761a084768d?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NjJ8fGJpa2luZyUyMGNvdXBsZXxlbnwwfHwwfHx8Mg%3D%3D",
                            Title = "Bike ride"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Try horseback riding for a unique experience.",
                            ImageUrl = "https://images.unsplash.com/photo-1638103188975-08f3ad6ae623?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTA0fHxob3JzZWJhY2slMjByaWRpbmd8ZW58MHx8MHx8fDI%3D",
                            Title = "Horseback riding"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Challenge yourselves with an escape room game.",
                            ImageUrl = "https://images.unsplash.com/photo-1585864731036-6ab6fb54f063?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjF8fGVzY2FwZSUyMHJvb218ZW58MHx8MHx8fDI%3D",
                            Title = "Escape room"
                        });
                });

            modelBuilder.Entity("DateSwipe.Shared.DateIdeaCategory", b =>
                {
                    b.Property<int>("DateIdeaId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("DateIdeaId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("DateIdeaCategories");

                    b.HasData(
                        new
                        {
                            DateIdeaId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            DateIdeaId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            DateIdeaId = 3,
                            CategoryId = 2
                        },
                        new
                        {
                            DateIdeaId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            DateIdeaId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            DateIdeaId = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            DateIdeaId = 7,
                            CategoryId = 2
                        },
                        new
                        {
                            DateIdeaId = 8,
                            CategoryId = 6
                        },
                        new
                        {
                            DateIdeaId = 9,
                            CategoryId = 2
                        },
                        new
                        {
                            DateIdeaId = 10,
                            CategoryId = 1
                        },
                        new
                        {
                            DateIdeaId = 11,
                            CategoryId = 4
                        },
                        new
                        {
                            DateIdeaId = 12,
                            CategoryId = 6
                        },
                        new
                        {
                            DateIdeaId = 13,
                            CategoryId = 4
                        },
                        new
                        {
                            DateIdeaId = 14,
                            CategoryId = 6
                        },
                        new
                        {
                            DateIdeaId = 15,
                            CategoryId = 6
                        },
                        new
                        {
                            DateIdeaId = 16,
                            CategoryId = 4
                        },
                        new
                        {
                            DateIdeaId = 17,
                            CategoryId = 2
                        },
                        new
                        {
                            DateIdeaId = 18,
                            CategoryId = 4
                        },
                        new
                        {
                            DateIdeaId = 19,
                            CategoryId = 4
                        },
                        new
                        {
                            DateIdeaId = 20,
                            CategoryId = 4
                        });
                });

            modelBuilder.Entity("DateSwipe.Shared.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("DateSwipe.Shared.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoupleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSubscribed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DateSwipe.Shared.UserSwipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoupleId")
                        .HasColumnType("int");

                    b.Property<int>("DateIdeaId")
                        .HasColumnType("int");

                    b.Property<bool>("Liked")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSwipes");
                });

            modelBuilder.Entity("DateSwipe.Shared.DateIdeaCategory", b =>
                {
                    b.HasOne("DateSwipe.Shared.Category", "Category")
                        .WithMany("DateIdeaCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DateSwipe.Shared.DateIdea", "DateIdea")
                        .WithMany("DateIdeaCategories")
                        .HasForeignKey("DateIdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("DateIdea");
                });

            modelBuilder.Entity("DateSwipe.Shared.UserSwipe", b =>
                {
                    b.HasOne("DateSwipe.Shared.User", "User")
                        .WithMany("UserSwipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DateSwipe.Shared.Category", b =>
                {
                    b.Navigation("DateIdeaCategories");
                });

            modelBuilder.Entity("DateSwipe.Shared.DateIdea", b =>
                {
                    b.Navigation("DateIdeaCategories");
                });

            modelBuilder.Entity("DateSwipe.Shared.User", b =>
                {
                    b.Navigation("UserSwipes");
                });
#pragma warning restore 612, 618
        }
    }
}
